#!/bin/bash

##
## Install ZeroMQ dependencies. TO be invoked on the remote machine.
##


cd ${HOME}

# Install ZeroMQ
wget https://github.com/zeromq/libzmq/releases/download/v4.3.2/zeromq-4.3.2.tar.gz
tar xf zeromq-4.3.2.tar.gz
rm zeromq-4.3.2.tar.gz
cd zeromq-4.3.2
./configure --with-libsodium=no
sudo make
sudo make install
sudo ldconfig
sudo mv /home/ubuntu/dorylus/src/common/zmq.hpp /usr/local/include
cd ..
