#!/bin/bash

##
## Install requried dependencies to all the machines listed in ec2 manager, depending on their roles.
##
## Usage: $ ./gnnman/install-dep
##
## Options:
##      Default: Install the following dependencies:
##          Graphserver  - Basics like `build-essnetial`, Boost, ZeroMQ, AWSSDK-CPP
##          Weightserver - Basics like `build-essnetial`, Boost, ZeroMQ
##
## You might be prompted to enter the sudo passwd on remote machines.
##


cd $( dirname $0 )/..

EC2MAN_CMD="python3 -m ec2man"


# TODO: Maybe make the installation procedure multi-threaded?


# For graph servers.
#echo "Processing context 'graph'..."
#NUM_GRAPH_NODES=$(( $( ${EC2MAN_CMD} graph info | wc -l | awk '{print $1}' ) - 1 ))
#for i in $( seq 0 $(( ${NUM_GRAPH_NODES} - 1 )) ); do
#    sleep 15
#    ${EC2MAN_CMD} graph $i ssh -t "./dorylus/gnnman/helpers/graphserver.install"
#    sleep 15
#done


# For weight servers.
echo "Processing context 'weight'..."
NUM_GRAPH_NODES=$(( $( ${EC2MAN_CMD} weight info | wc -l | awk '{print $1}' ) - 1 ))
for i in $( seq 0 $(( ${NUM_GRAPH_NODES} - 1 )) ); do
    sleep 15
    ${EC2MAN_CMD} weight $i ssh -t "./dorylus/gnnman/helpers/weightserver.install"
    sleep 15
done

